# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtDesigner/configure.ui'
#
# Created: Fri Jan 15 16:29:40 2010
#      by: PyQt4 UI code generator 4.6.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(354, 349)
        self.groupBoxDistance = QtGui.QGroupBox(Dialog)
        self.groupBoxDistance.setGeometry(QtCore.QRect(10, 130, 331, 51))
        self.groupBoxDistance.setObjectName("groupBoxDistance")
        self.radioButtonKm = QtGui.QRadioButton(self.groupBoxDistance)
        self.radioButtonKm.setGeometry(QtCore.QRect(150, 20, 91, 23))
        self.radioButtonKm.setObjectName("radioButtonKm")
        self.radioButtonMi = QtGui.QRadioButton(self.groupBoxDistance)
        self.radioButtonMi.setGeometry(QtCore.QRect(250, 20, 83, 23))
        self.radioButtonMi.setChecked(True)
        self.radioButtonMi.setObjectName("radioButtonMi")
        self.labelDistance = QtGui.QLabel(self.groupBoxDistance)
        self.labelDistance.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.labelDistance.setObjectName("labelDistance")
        self.groupBoxTemperature = QtGui.QGroupBox(Dialog)
        self.groupBoxTemperature.setGeometry(QtCore.QRect(10, 70, 331, 51))
        self.groupBoxTemperature.setObjectName("groupBoxTemperature")
        self.radioButtonFahrenheit = QtGui.QRadioButton(self.groupBoxTemperature)
        self.radioButtonFahrenheit.setGeometry(QtCore.QRect(151, 16, 91, 23))
        self.radioButtonFahrenheit.setObjectName("radioButtonFahrenheit")
        self.labelTemperature = QtGui.QLabel(self.groupBoxTemperature)
        self.labelTemperature.setGeometry(QtCore.QRect(10, 18, 131, 20))
        self.labelTemperature.setObjectName("labelTemperature")
        self.radioButtonCelcius = QtGui.QRadioButton(self.groupBoxTemperature)
        self.radioButtonCelcius.setGeometry(QtCore.QRect(247, 17, 83, 23))
        self.radioButtonCelcius.setChecked(True)
        self.radioButtonCelcius.setObjectName("radioButtonCelcius")
        self.groupWoeid = QtGui.QGroupBox(Dialog)
        self.groupWoeid.setGeometry(QtCore.QRect(10, 10, 331, 51))
        self.groupWoeid.setObjectName("groupWoeid")
        self.lineEditWoeid = QtGui.QLineEdit(self.groupWoeid)
        self.lineEditWoeid.setGeometry(QtCore.QRect(132, 14, 113, 23))
        self.lineEditWoeid.setMaxLength(8)
        self.lineEditWoeid.setObjectName("lineEditWoeid")
        self.labelId = QtGui.QLabel(self.groupWoeid)
        self.labelId.setGeometry(QtCore.QRect(10, 20, 101, 17))
        self.labelId.setObjectName("labelId")
        self.pushButtonOk = QtGui.QPushButton(Dialog)
        self.pushButtonOk.setGeometry(QtCore.QRect(110, 310, 113, 32))
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.pushButtonCancel = QtGui.QPushButton(Dialog)
        self.pushButtonCancel.setGeometry(QtCore.QRect(230, 310, 113, 32))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.groupWind = QtGui.QGroupBox(Dialog)
        self.groupWind.setGeometry(QtCore.QRect(10, 190, 331, 51))
        self.groupWind.setObjectName("groupWind")
        self.radioButtonKph = QtGui.QRadioButton(self.groupWind)
        self.radioButtonKph.setGeometry(QtCore.QRect(150, 16, 83, 23))
        self.radioButtonKph.setObjectName("radioButtonKph")
        self.labelWind = QtGui.QLabel(self.groupWind)
        self.labelWind.setGeometry(QtCore.QRect(10, 20, 131, 20))
        self.labelWind.setObjectName("labelWind")
        self.radioButtonMph = QtGui.QRadioButton(self.groupWind)
        self.radioButtonMph.setGeometry(QtCore.QRect(247, 17, 83, 23))
        self.radioButtonMph.setChecked(True)
        self.radioButtonMph.setObjectName("radioButtonMph")
        self.groupBoxPressure = QtGui.QGroupBox(Dialog)
        self.groupBoxPressure.setGeometry(QtCore.QRect(10, 250, 331, 51))
        self.groupBoxPressure.setObjectName("groupBoxPressure")
        self.radioButtonIn = QtGui.QRadioButton(self.groupBoxPressure)
        self.radioButtonIn.setGeometry(QtCore.QRect(250, 20, 83, 23))
        self.radioButtonIn.setObjectName("radioButtonIn")
        self.labelPressure = QtGui.QLabel(self.groupBoxPressure)
        self.labelPressure.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.labelPressure.setObjectName("labelPressure")
        self.radioButtonMb = QtGui.QRadioButton(self.groupBoxPressure)
        self.radioButtonMb.setGeometry(QtCore.QRect(150, 20, 83, 23))
        self.radioButtonMb.setChecked(True)
        self.radioButtonMb.setObjectName("radioButtonMb")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditWoeid, self.radioButtonFahrenheit)
        Dialog.setTabOrder(self.radioButtonFahrenheit, self.radioButtonCelcius)
        Dialog.setTabOrder(self.radioButtonCelcius, self.radioButtonKm)
        Dialog.setTabOrder(self.radioButtonKm, self.radioButtonMi)
        Dialog.setTabOrder(self.radioButtonMi, self.radioButtonKph)
        Dialog.setTabOrder(self.radioButtonKph, self.radioButtonMph)
        Dialog.setTabOrder(self.radioButtonMph, self.radioButtonMb)
        Dialog.setTabOrder(self.radioButtonMb, self.radioButtonIn)
        Dialog.setTabOrder(self.radioButtonIn, self.pushButtonOk)
        Dialog.setTabOrder(self.pushButtonOk, self.pushButtonCancel)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonKm.setText(QtGui.QApplication.translate("Dialog", "&Kilometers", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonMi.setText(QtGui.QApplication.translate("Dialog", "&Miles", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDistance.setText(QtGui.QApplication.translate("Dialog", "Show Distance in", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonFahrenheit.setText(QtGui.QApplication.translate("Dialog", "&Fahrenheit", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTemperature.setText(QtGui.QApplication.translate("Dialog", "Show Temperature in", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCelcius.setText(QtGui.QApplication.translate("Dialog", "C&elcius", None, QtGui.QApplication.UnicodeUTF8))
        self.labelId.setText(QtGui.QApplication.translate("Dialog", "Woeid ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOk.setText(QtGui.QApplication.translate("Dialog", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("Dialog", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonKph.setText(QtGui.QApplication.translate("Dialog", "K&ph", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWind.setText(QtGui.QApplication.translate("Dialog", "Show Wind Speed in", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonMph.setText(QtGui.QApplication.translate("Dialog", "Mp&h", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonIn.setText(QtGui.QApplication.translate("Dialog", "&In", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPressure.setText(QtGui.QApplication.translate("Dialog", "Show Pressure in", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonMb.setText(QtGui.QApplication.translate("Dialog", "M&b", None, QtGui.QApplication.UnicodeUTF8))

