# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtDesigner/weather.ui'
#
# Created: Wed Mar 17 15:11:14 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Weather(object):
    def setupUi(self, Weather):
        Weather.setObjectName("Weather")
        Weather.resize(394, 230)
        self.frame = QtGui.QFrame(Weather)
        self.frame.setGeometry(QtCore.QRect(20, 10, 64, 64))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelIcon = QtGui.QLabel(self.frame)
        self.labelIcon.setGeometry(QtCore.QRect(0, 0, 64, 64))
        self.labelIcon.setObjectName("labelIcon")
        self.labelFSunset = QtGui.QLabel(Weather)
        self.labelFSunset.setGeometry(QtCore.QRect(20, 80, 56, 18))
        self.labelFSunset.setObjectName("labelFSunset")
        self.labelSunset = QtGui.QLabel(Weather)
        self.labelSunset.setGeometry(QtCore.QRect(130, 80, 61, 18))
        self.labelSunset.setObjectName("labelSunset")
        self.labelFSunrise = QtGui.QLabel(Weather)
        self.labelFSunrise.setGeometry(QtCore.QRect(20, 110, 56, 18))
        self.labelFSunrise.setObjectName("labelFSunrise")
        self.labelSunrise = QtGui.QLabel(Weather)
        self.labelSunrise.setGeometry(QtCore.QRect(130, 110, 61, 18))
        self.labelSunrise.setObjectName("labelSunrise")
        self.labelTemp = QtGui.QLabel(Weather)
        self.labelTemp.setGeometry(QtCore.QRect(100, 20, 281, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTemp.setFont(font)
        self.labelTemp.setObjectName("labelTemp")
        self.labelFWindChill = QtGui.QLabel(Weather)
        self.labelFWindChill.setGeometry(QtCore.QRect(20, 140, 71, 18))
        self.labelFWindChill.setObjectName("labelFWindChill")
        self.labelWindChill = QtGui.QLabel(Weather)
        self.labelWindChill.setGeometry(QtCore.QRect(130, 140, 61, 18))
        self.labelWindChill.setObjectName("labelWindChill")
        self.labelFWindSpeed = QtGui.QLabel(Weather)
        self.labelFWindSpeed.setGeometry(QtCore.QRect(20, 170, 81, 18))
        self.labelFWindSpeed.setObjectName("labelFWindSpeed")
        self.labelWindSpeed = QtGui.QLabel(Weather)
        self.labelWindSpeed.setGeometry(QtCore.QRect(130, 170, 61, 18))
        self.labelWindSpeed.setObjectName("labelWindSpeed")
        self.labelFWindDirection = QtGui.QLabel(Weather)
        self.labelFWindDirection.setGeometry(QtCore.QRect(20, 200, 101, 18))
        self.labelFWindDirection.setObjectName("labelFWindDirection")
        self.labelWindDirection = QtGui.QLabel(Weather)
        self.labelWindDirection.setGeometry(QtCore.QRect(130, 200, 61, 18))
        self.labelWindDirection.setObjectName("labelWindDirection")
        self.labelFPressure = QtGui.QLabel(Weather)
        self.labelFPressure.setGeometry(QtCore.QRect(210, 140, 71, 18))
        self.labelFPressure.setObjectName("labelFPressure")
        self.labelFHumidity = QtGui.QLabel(Weather)
        self.labelFHumidity.setGeometry(QtCore.QRect(210, 80, 61, 18))
        self.labelFHumidity.setObjectName("labelFHumidity")
        self.labelVisibility = QtGui.QLabel(Weather)
        self.labelVisibility.setGeometry(QtCore.QRect(290, 110, 61, 21))
        self.labelVisibility.setObjectName("labelVisibility")
        self.labelPressure = QtGui.QLabel(Weather)
        self.labelPressure.setGeometry(QtCore.QRect(290, 140, 81, 18))
        self.labelPressure.setObjectName("labelPressure")
        self.labelFVisibility = QtGui.QLabel(Weather)
        self.labelFVisibility.setGeometry(QtCore.QRect(210, 110, 56, 18))
        self.labelFVisibility.setObjectName("labelFVisibility")
        self.labelHumidity = QtGui.QLabel(Weather)
        self.labelHumidity.setGeometry(QtCore.QRect(290, 80, 61, 16))
        self.labelHumidity.setObjectName("labelHumidity")
        self.labelRising = QtGui.QLabel(Weather)
        self.labelRising.setGeometry(QtCore.QRect(290, 170, 61, 18))
        self.labelRising.setObjectName("labelRising")
        self.labelFRising = QtGui.QLabel(Weather)
        self.labelFRising.setGeometry(QtCore.QRect(210, 170, 71, 18))
        self.labelFRising.setObjectName("labelFRising")
        self.labelFLastUpdate = QtGui.QLabel(Weather)
        self.labelFLastUpdate.setGeometry(QtCore.QRect(298, 213, 56, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.labelFLastUpdate.setFont(font)
        self.labelFLastUpdate.setObjectName("labelFLastUpdate")
        self.labelLastUpdate = QtGui.QLabel(Weather)
        self.labelLastUpdate.setGeometry(QtCore.QRect(353, 213, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.labelLastUpdate.setFont(font)
        self.labelLastUpdate.setObjectName("labelLastUpdate")

        self.retranslateUi(Weather)
        QtCore.QMetaObject.connectSlotsByName(Weather)

    def retranslateUi(self, Weather):
        Weather.setWindowTitle(QtGui.QApplication.translate("Weather", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFSunset.setText(QtGui.QApplication.translate("Weather", "Sunset", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSunset.setText(QtGui.QApplication.translate("Weather", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFSunrise.setText(QtGui.QApplication.translate("Weather", "Sunrise", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSunrise.setText(QtGui.QApplication.translate("Weather", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTemp.setText(QtGui.QApplication.translate("Weather", "22 c Scattered Thunderstorms", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFWindChill.setText(QtGui.QApplication.translate("Weather", "Feels like ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWindChill.setText(QtGui.QApplication.translate("Weather", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFWindSpeed.setText(QtGui.QApplication.translate("Weather", "Wind Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWindSpeed.setText(QtGui.QApplication.translate("Weather", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFWindDirection.setText(QtGui.QApplication.translate("Weather", "Wind Direction", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWindDirection.setText(QtGui.QApplication.translate("Weather", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFPressure.setText(QtGui.QApplication.translate("Weather", "Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFHumidity.setText(QtGui.QApplication.translate("Weather", "Humidity", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVisibility.setText(QtGui.QApplication.translate("Weather", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPressure.setText(QtGui.QApplication.translate("Weather", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFVisibility.setText(QtGui.QApplication.translate("Weather", "Visibility", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHumidity.setText(QtGui.QApplication.translate("Weather", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRising.setText(QtGui.QApplication.translate("Weather", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFRising.setText(QtGui.QApplication.translate("Weather", "Tendancy", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFLastUpdate.setText(QtGui.QApplication.translate("Weather", "last update:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLastUpdate.setText(QtGui.QApplication.translate("Weather", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))

